In [4]:
import numpy as np

# Check NumPy version
print("NumPy Version:", np.__version__)

# Check available NumPy methods
print(dir(np))


NumPy Version: 2.2.4
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array

In [5]:
# Creating NumPy Arrays
# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Creating a 2D array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
# Checking Data Type and Shape
print("Data Type:", arr1.dtype)  # int64 or int32
print("Shape:", arr2.shape)  # (rows, columns)
print("Size:", arr2.size)  # Total number of elements


Data Type: int64
Shape: (2, 3)
Size: 6


In [7]:
# Array Operations (Vectorized Operations)
# Arithmetic Operations
arr3 = np.array([10, 20, 30])
print("Addition:", arr3 + 5)
print("Multiplication:", arr3 * 2)

# Element-wise operations
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])
print("Element-wise Sum:", arr4 + arr5)
print("Element-wise Product:", arr4 * arr5)


Addition: [15 25 35]
Multiplication: [20 40 60]
Element-wise Sum: [5 7 9]
Element-wise Product: [ 4 10 18]


In [8]:
# Statistical Operations
data = np.array([10, 20, 30, 40, 50, 60, 70])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))


Mean: 40.0
Median: 40.0
Standard Deviation: 20.0
Variance: 400.0


In [9]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Elements greater than 5:", arr[arr > 5])


Elements greater than 5: [6 7 8 9]


In [10]:
# Reshaping and Resizing Arrays
arr6 = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr6.reshape(2, 3)
print("Reshaped Array:\n", reshaped)


Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [11]:
# Creating Special Arrays
print("Zeros Array:\n", np.zeros((3, 3)))
print("Ones Array:\n", np.ones((2, 4)))
print("Random Numbers:\n", np.random.rand(3, 3))


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random Numbers:
 [[0.91483315 0.71553463 0.21872802]
 [0.3209212  0.80626283 0.9373105 ]
 [0.38099481 0.02768706 0.64752818]]
